app_pkg/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from app_pkg import db, login


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True, unique=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    type = db.Column(db.String(20), index=True)
    password_hash = db.Column(db.String(128))

    def __repr__(self):
        return f"<User: {self.username}, Email: {self.email}, User Type: {self.type}>"

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)


@login.user_loader
def load_user(uid):
    return User.query.get(int(uid))


class Quiz(db.Model):
    id = db.Column(db.Integer, primary_key=True, unique=True)
    name = db.Column(db.String(255), index=True)
    pin = db.Column(db.String(64), index=True, unique=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return f"<Quiz {self.id} with name <<{self.name}>> by Lecturer {self.user_id}>"


class Question(db.Model):
    id = db.Column(db.Integer, primary_key=True, unique=True)
    quiz_id = db.Column(db.Integer, db.ForeignKey('quiz.id'))
    question = db.Column(db.String(255), index=True)
    choice_a = db.Column(db.String(255), index=True)
    choice_b = db.Column(db.String(255), index=True)
    choice_c = db.Column(db.String(255), index=True)
    choice_d = db.Column(db.String(255), index=True)
    answer = db.Column(db.String(255), index=True)

    def __repr__(self):
        return f"<Question {self.id}: {self.type} type, {self.question}," \
               f"{[self.choice_a, self.choice_b, self.choice_c, self.choice_d]}, answer: {self.answer}> "


class Score(db.Model):
    id = db.Column(db.Integer, primary_key=True, unique=True)
    quiz_id = db.Column(db.Integer, db.ForeignKey('quiz.id'))
    score = db.Column(db.Integer)
    rank_score = db.Column(db.Integer)
    student_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return f"<Mark of {self.score} with score of {self.rank_score} on number {self.quiz_id} quiz for student {self.student_id}>"

app_pkg/templates/Signup.html
{% extends "base.html" %}
{% block content %}
    <!-- body class="signup" -->
    <div class="signup">
        <div class="header">
            <nav>
                <image src="../static/css/logo.png" class="logo"></image>
                <h1><a href="/">Happy Learning</a></h1>
            </nav>
        </div>
        <div class="signupbox">
            <form>
                <div class="welcome">
                    <h1>Happy Learning</h1>
                    <h3>Get Start Now</h3>
                </div>

                <input type="text" name="" placeholder="Full Name"/>

                <input type="text" name="" placeholder="Enter Email"/>

                <input type="password" name="" placeholder="Password"/>

                <input type="password" name="" placeholder="Confirm Password"/>

                <input type="date" placeholder="Confirm Password"/>
                <br>

                <a href="#"><input type="submit" name="" value="Create Account and Login"></a>

                <a type="link" href="/login">Already have an account?</a>
                
            </form>
        </div>
    </div>
{% endblock %}

app_pkg/templates/about.html
{% extends "base.html" %}
{% block content %}

    <body id="aboutUs">
    <div class="header">
        <nav>
            <a href="/">
                <image src="{{ url_for('static', filename='images/logo.png') }}" class="logo"></image>
            </a>
            <h1><a href="/">Happy Learning</a></h1>
            <ul class="nav-links">
                <a href="/">
                    <li class="btn">Home</li>
                </a>
            </ul>
        </nav>
    </div>
    <img src="{{ url_for('static', filename='images/aboutus_box.png') }}"
         style="zoom:100%; position:fixed; left:80px; top:180px;" alt="">
    <img src="{{ url_for('static', filename='images/contactus_box.png') }}"
         style="zoom: 101%; position:fixed; left:80px; top:500px; border-radius: 20px; box-shadow:-2px 2px rgba(169, 169, 169, 0.675);"
         alt="">
    </body>

{% endblock %}

app_pkg/templates/edit_question.html
{% extends "base.html" %}
{% block content %}
    <head>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
        <script type="text/javascript">
            $(window).on('load', () => {
                if ($('input[type=checkbox]:checked').length >= 1) {
                    $('input[type=checkbox]').not(":checked").attr("disabled", true);
                    $('input[type=submit]').removeAttr('disabled');
                } else {
                    $('input[type=checkbox]').not(":checked").removeAttr('disabled');
                    $('input[type=submit]').attr("disabled", true);
                }
                $('input[type=checkbox]').click(function () {
                    if ($('input[type=checkbox]:checked').length >= 1) {
                        $('input[type=checkbox]').not(":checked").attr("disabled", true);
                        $('input[type=submit]').removeAttr('disabled');
                    } else {
                        $('input[type=checkbox]').not(":checked").removeAttr('disabled');
                        $('input[type=submit]').attr("disabled", true);
                    }
                });
            });
        </script>
        <title>Edit Question</title>
    </head>

    <body id="editQuestion">
    <div class="header">
        <nav>
            <a href="/">
                <image src="{{ url_for('static', filename='images/logo.png') }}" class="logo"></image>
            </a>
            <h1><a>Happy Learning</a></h1>
        </nav>
    </div>

    {% if question %}
        <form id="editQuestionForm" name="question-form" action="" method="post">
            {{ form.hidden_tag() }}
            <p>
                {{ form.question.label }}<br>
                {{ form.question() }}
                {% for error in form.question.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
            <p>
                {{ form.choice_a.label }}<br>
                {{ form.checkbox_a() }}
                {{ form.choice_a() }}
                {% for error in form.choice_a.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
            <p>
                {{ form.choice_b.label }}<br>
                {{ form.checkbox_b() }}
                {{ form.choice_b() }}
                {% for error in form.choice_b.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
            <p>
                {{ form.choice_c.label }}<br>
                {{ form.checkbox_c() }}
                {{ form.choice_c() }}
                {% for error in form.choice_c.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
            <p>
                {{ form.choice_d.label }}<br>
                {{ form.checkbox_d() }}
                {{ form.choice_d() }}
                {% for error in form.choice_d.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
            <p>
                {{ form.submit() }}
            </p>

            <a href="/delete_question/{{ question.id }}">
                <input type="button" id="add-btn_start" value="Delete This Question">
            </a>
        </form>
        <a href="javascript:history.go(-1)">
            <button id="del-quiz-btn">Back to Quiz</button>
        </a>
    {% endif %}
    </body>

{% endblock %}

app_pkg/templates/edit_quiz.html
{% extends "base.html" %}
{% block content %}

    <body id="editQuiz">
    <div class="header">
        <nav>
            <a href="/">
                <image src="{{ url_for('static', filename='images/logo.png') }}" class="logo"></image>
            </a>
            <h1><a href="/">Happy Learning</a></h1>
        </nav>
    </div>

    <form name="quiz-name-form" id="quizNameForm" action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.name.label }}
            {{ form.name(value=quiz.name) }}
        </p>
        <p>{{ form.submit() }}</p>
    </form>

    <div id="questionList">
        {% if question_set %}
            {% for a_question in question_set %}
                <div class="singleQuestionEntry">
                    <a href="/edit_question/{{ quiz.id }}/?id={{ a_question.id }}"
                       style="text-decoration: none;">
                        <p>Question: {{ a_question.question }}</p>
                        <p>A: {{ a_question.choice_a }}</p>
                        <p>B: {{ a_question.choice_b }}</p>
                        <p>C: {{ a_question.choice_c }}</p>
                        <p>D: {{ a_question.choice_d }}</p>
                        <p>Answer: {{ a_question.answer }}</p>
                    </a>
                </div>
            {% endfor %}
        {% endif %}
    </div>

    <a href="/edit_quiz/quiz_history/{{ quiz.id }}">
        <button id="historyBtn">Quiz History</button>
    </a>
    <a href="/create_question/{{ quiz.id }}">
        <button id="addQuizBtn">Add A Question</button>
    </a>
    <a href="/quiz_play/{{ quiz.pin }}">
        <button id="add-btn_start">Start This Quiz</button>
    </a>
    <a href="{{ url_for("lecturer_main") }}">
        <button id="go-back-btn">Back to All Quizzes</button>
    </a>
    <a href="/delete_quiz/?id={{ quiz.id }}">
        <button id="del-quiz-btn">Delete This Quiz</button>
    </a>
    </body>

{% endblock %}

app_pkg/templates/history.html
<!DOCTYPE html>
<html>

<head>
	<meta http-equiv="content-type" content="text/html" charset="utf-8" />
	<title>about us&contact us</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<link rel="StyleSheet" href="../static/css/style.css" />
	<script src="https://secure.exportkit.com/cdn/js/ek_googlefonts.js?v=6"></script>

</head>
<style>
body {
	margin: 0;
	padding: 0;
	background-image: url('../static/css/aboutus.png');
	background-repeat: no-repeat;
	background-attachment: fixed;
	background-size: cover;
}
</style>
<body>
	<div class="content-container">
		<div class="header">
			<div class="logo">
				<a href="#">
					<img src="../static/css/logo.png" alt="logo" />
					<span class="title">HAPPY LEARNING</span>
				</a>
			</div>
			<div class="search">
				<input type="text" placeholder="Search" />
				<div class="search-icon"></div>
			</div>
			<div class="functions">
				<a href="#" class="block">
					<span>Read Page</span>
					<img src="../static/css/volume_max.png" />
				</a>
				<a href="#" class="block">
					<img src="../static/css/group.png" />
					<span>Classes</span>
					<img src="../static/css/down_arrow.png" />
				</a>
			</div>
			<div class="join-us">
				<a href="#">Join Us</a>
			</div>
		</div>

	</div>
</body>

</html>

app_pkg/templates/login.html
{% extends "base.html" %}
{% block content %}
    <body id="login">
    <div class="header">
        <nav>
            <a href="/">
                <image src="{{ url_for('static', filename='images/logo.png') }}" class="logo"></image>
            </a>
            <h1><a href="/">Happy Learning</a></h1>
            <label for="tips">{{ tips }}</label>
        </nav>
    </div>
    <div id="loginForm">
        <div class="welcome">
            <h1>Welcome</h1>
            <h3>Login into your account</h3>
        </div>
        <form name="login-form" action="" method="post" autocomplete="on">
            {{ form.hidden_tag() }}
            <p>
                {{ form.email.label }}<br>
                {{ form.email() }}<br>
                {% for error in form.email.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
            <p>
                {{ form.password.label }}<br>
                {{ form.password() }}
                {% for error in form.password.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
            <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
            <p>{{ form.submit() }}</p>
        </form>
        <p>New User? <a href="{{ url_for('register') }}">Click to Register!</a></p>
        <a href="#">Forgot password?</a>
    </div>
    </body>
{% endblock %}

app_pkg/templates/quiz_history.html
{% extends "base.html" %}
{% block content %}
    <body id="quizHistory">
    <table id="scoreBoardTable">
        <tr>
            <th>Usernames</th>
            <th>Marks</th>
            <th>Scores</th>
        </tr>
        {% for row in score_join_user %}
            <tr>
                <td>{{ row[1].username }}</td>
                <td>{{ row[0].score }}/{{ num_of_questions }}</td>
                <td>{{ row[0].rank_score }}</td>
            </tr>
        {% endfor %}
    </table>
    <a href="javascript:history.go(-1)">
        <button id="del-quiz-btn">Back to Quiz</button>
    </a>
    </body>
{% endblock %}

app_pkg/templates/quiz_lecturer.html
{% extends "base.html" %}
{% block content %}
    <div class="lecturer-list">
        <div class="header">
            <nav>
                <image src="../static/images/logo.png" class="logo"></image>
            </nav>
        </div>
    
        <div class="dropdown">
            <button class="drop-btn">{{current_user.username}}</button>
                <div class="dropdown-content">
                    <a href="#">Switch Account</a>
                    <a href="/login">Log Out</a>
                </div>
        </div>
        <div class="quiz-creation" id="test">
            <form name="add-question" action="" method="post">
                {{ form.hidden_tag() }}
                <p>
                    {{ form.question.label }}<br>
                    {{ form.question(placeholder="Question") }}
                    {% for error in form.email.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                    {% endfor %}
                </p>
                <p>
                    {{ form.choice_a.label }}<br>
                    {{ form.checkbox_a }}
                    {{ form.choice_a(placeholder="add options") }}
                    {% for error in form.password.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                    {% endfor %}
                </p>
                <p>
                    {{ form.choice_b.label }}<br>
                    {{ form.checkbox_b }}
                    {{ form.choice_b(placeholder="add options") }}
                    {% for error in form.password.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                    {% endfor %}
                </p>
                <p>
                    {{ form.choice_c.label }}<br>
                    {{ form.checkbox_c }}
                    {{ form.choice_c(placeholder="add options") }}
                    {% for error in form.password.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                    {% endfor %}
                </p>
                <p>
                    {{ form.choice_d.label }}<br>
                    {{ form.checkbox_d }}
                    {{ form.choice_d(placeholder="add options") }}
                    {% for error in form.password.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                    {% endfor %}
                </p>
                <p>{{ form.submit() }}</p>
            </form>
        </div>
        
    </div>

<script>
function displayFeedback() {
  let prompt = 'Upload successfully!'
  alert(prompt);
}
</script>

{% endblock %}

app_pkg/templates/quiz_play.html
{% extends "base.html" %}
{% block content %}
    <head>
        <title>Quiz Play Room</title>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.5.2/socket.io.js"></script>
        <script type="text/javascript">
            // add prev and next method to array type
            Array.prototype.next = function () {
                return this[++this.current];
            };
            Array.prototype.prev = function () {
                return this[--this.current];
            };
            Array.prototype.current = 0;</script>
        <script type="text/javascript">
            let socket = io.connect();
            const abcd = "ABCD";

            $(document).ready(() => {
                socket.on("connect", () => {
                    socket.emit("join", "{{ PIN }}");
                })
                socket.on("disconnect", () => {
                    socket.emit("leave", "{{ PIN }}");
                })
                socket.on("message", (data) => {
                    $('#players').append($('<p>').text(data));
                })
            })

            function getDescendingSortedHash(inputHash) {
                let resultHash = {};

                let keys = Object.keys(inputHash);
                keys.sort(function (a, b) {
                    return inputHash[a] - inputHash[b]
                }).reverse().forEach(function (k) {
                    resultHash[k] = inputHash[k];
                });
                return resultHash;
            }

            function handler(e) {
                e.stopPropagation();
                e.preventDefault();
            }
            let questions = {{ the_quiz|safe }};
            let currentQuestion = JSON.parse(JSON.stringify(questions[questions.current]));
            let answer;
            let questionLaunchTime;
            let userChoice;

            let studentAnswers = {"quiz_id": {{quiz_id}}};

            $(window).on('load', () => {
                socket.on("show-finish-quiz", (top_three) => {
                    $('#onGoingQuestion').hide();
                    $('#quizFinish').show();
                    let theTags = document.getElementById("quizFinish").getElementsByTagName("span");
                    for (let i = 0; i < Object.keys(top_three).length * 2 - 1; i += 2) {
                        theTags[i].innerText = Object.keys(top_three)[i / 2];
                        theTags[i + 1].innerText = top_three[Object.keys(top_three)[i / 2]];
                    }
                })
                socket.on("show-question-block", () => {
                    $('#waiting').hide();
                    $('#onGoingQuestion').show();
                })
                socket.on("show-countdown-block", () => {
                    $('#countdown').show();
                });
                socket.on("receive-enable-choice", () => {
                    document.removeEventListener("click", handler, true);
                })
                socket.on("receive-reset-countdown", () => {
                    $('#countdown').hide();
                    $('#checkScoreBoard').show();
                    document.getElementById('beginCountdown').value = 10;
                    document.getElementById('beginCountdownText').innerText = "10";
                    document.getElementById(answer).setAttribute("class", "answer");
                    if ("{{ current_user.type}}" === "student" && !(userChoice === answer)) {
                        if (!(userChoice === undefined)) {
                            document.getElementById(userChoice).setAttribute("class", "wrong");
                        } else {
                            socket.emit("calculate-rank-score", questionLaunchTime, Date.now(), false, "{{ PIN }}");
                        }
                    }
                })
                socket.on("receive-one-second", () => {
                    let timeLeft = Number(document.getElementById('beginCountdown').value);
                    timeLeft = Number(document.getElementById('beginCountdown').value) - 1;
                    return new Promise((resolve, reject) => {
                        document.getElementById('beginCountdown').value = timeLeft;
                        document.getElementById('beginCountdownText').textContent = timeLeft.toString();
                        if (timeLeft === 0) {
                            socket.emit("ask-reset-countdown", "{{ PIN }}");
                        }
                    });
                })
                socket.on("show-populate-scoreboard", (rankScores) => {
                    $('#checkScoreBoard').hide();
                    $('#onGoingQuestion').hide();
                    $('#scoreBoard').show();
                    $('#nextBtn').show();
                    rankScores = getDescendingSortedHash(rankScores);
                    let html = "";
                    for (let i = 0; i < Object.keys(rankScores).length; i++) {
                        html = "<tr><td>" + (i + 1) + "</td><td>" + Object.keys(rankScores)[i] + "</td>" +
                            "<td>" + rankScores[Object.keys(rankScores)[i]] + "</td></tr>";
                        document.getElementById("scoreBoardTable").innerHTML += html;
                    }
                })
                socket.on("show-question-content", () => {
                    questionLaunchTime = Date.now();
                    answer = currentQuestion.answer;
                    document.getElementById('question').innerHTML = currentQuestion.question;
                    document.getElementById('A').value = currentQuestion.choice_a;
                    document.getElementById('B').value = currentQuestion.choice_b;
                    document.getElementById('C').value = currentQuestion.choice_c;
                    document.getElementById('D').value = currentQuestion.choice_d;
                })
                socket.on("show-next-question", (rank_scores) => {
                    questionLaunchTime = Date.now();
                    document.getElementById('scoreBoardTable').innerHTML = "<caption>Score Board</caption><thead><tr><th>#</th><th>Usernames</th>" +
                        "<th>Score</th></tr></thead>";
                    $('#scoreBoard').hide();
                    $('#nextBtn').hide();
                    socket.emit("ask-prevent-choice", "{{ PIN }}");
                    let nextQuestion = questions.next();
                    if (!!nextQuestion) {
                        currentQuestion = JSON.parse(JSON.stringify(nextQuestion));
                        for (let letter in abcd) {
                            document.getElementById(abcd[letter]).removeAttribute("class");
                        }
                        socket.emit("ask-question-block", "{{ PIN }}");
                        socket.emit("ask-question-content", "{{ PIN }}");
                    } else {
                        if ("{{ current_user.type }}" === "student") {
                            studentAnswers["rank_score"] = rank_scores["{{ current_user.username }}"]
                            socket.emit("send-answer", studentAnswers, "{{ PIN }}");
                        } else {
                            socket.emit("ask-finish-quiz", "{{ quiz_id }}", "{{ PIN }}");
                        }
                    }
                })
                socket.on("show-select-choice", (choice) => {
                    let isCorrect = choice === answer;
                    studentAnswers[currentQuestion.id] = isCorrect;
                    socket.emit("calculate-rank-score", questionLaunchTime, Date.now(), isCorrect, "{{ PIN }}");
                    userChoice = choice;
                    document.getElementById(choice).setAttribute("class", "selected");
                    document.addEventListener("click", handler, true);
                })
                $('#exitRoomBtn').on('click', () => {
                    socket.emit("leave", "{{ PIN }}");
                })
                $('#startBtn').on('click', () => {
                    socket.emit("ask-question-block", "{{ PIN }}");
                    socket.emit("ask-question-content", "{{ PIN }}");
                    socket.emit("ask-countdown-block", "{{ PIN }}");
                    socket.emit("ask-countdown", "{{ PIN }}");
                })
                $('#checkScoreBoard').on('click', () => {
                    socket.emit("ask-scoreboard", "{{ PIN }}");
                })
                $('#nextBtn').on('click', () => {
                    $('#nextBtn').hide();
                    socket.emit("ask-next-question", "{{ PIN }}");
                    if (!(questions.current === (questions.length - 1))) {
                        socket.emit("ask-countdown-block", "{{ PIN }}");
                        socket.emit("ask-countdown", "{{ PIN }}");
                    }
                })
                if ("{{ current_user.type }}" === "student") {
                    $('#startBtn').hide();
                }
                if ("{{ current_user.type }}" === "student") {
                    $('#A').on('click', () => {
                        socket.emit("ask-choice-A");
                    })
                    $('#B').on('click', () => {
                        socket.emit("ask-choice-B");
                    })
                    $('#C').on('click', () => {
                        socket.emit("ask-choice-C");
                    })
                    $('#D').on('click', () => {
                        socket.emit("ask-choice-D");
                    })
                }
            })
        </script>
    </head>
    <body id="quizPlay">
    <div id="waiting" style="position:relative;top:40px;">
        <div style="text-align: center;">
            {% if current_user.type == "lecturer" %}
                <a href="/edit_quiz/{{ quiz_id }}">
                    <button id="exitRoomBtn">Exit</button>
                </a>
            {% else %}
                <a href="/index">
                    <button id="exitRoomBtn">Exit</button>
                </a>
            {% endif %}
            <button id="startBtn">Let's Go!!!</button>
            {% if current_user.type == "lecturer" %}
                <h3 id="quizPIN">The Game PIN: {{ PIN }}</h3>
                <div id="players"><p>Players:</p></div>
            {% else %}
                <p>Waiting for the lecturer to start the game...</p>
            {% endif %}
        </div>
    </div>

    {% if current_user.type == "lecturer" %}
        <input type="button" value="Check Scores" id="checkScoreBoard" hidden/>
        <input type="button" value="Next" id="nextBtn" hidden/>
    {% endif %}

    <div id="onGoingQuestion" hidden>
        <div id="countdown">
            <progress value="10" max="10" id="beginCountdown"></progress>
            <span>  <span id="beginCountdownText"> 10</span>S Left!!!</span>
        </div>
        <div style="text-align: center;font-size:60px;">Question: <span id="question"></span></div>
        <div id="choices">
            <input type="button" id="A" value=""/>
            <input type="button" id="B" value=""/>
            <br>
            <input type="button" id="C" value=""/>
            <input type="button" id="D" value=""/>
        </div>
    </div>

    <div id="quizFinish" hidden>Quiz Finished!<br>
        <a href="{{ url_for("index") }}">
            <input type="button" value="Go back to Home page">
        </a>
        <div id="champion">
            <img src="../static/images/first1.png"><br>
            <span id="champName"></span> won with <span id="champScore"></span>
        </div>
        <div id="firstRunnerUp">
            <img src="../static/images/first2.png"><br>
            <span id="secondName"></span> won with <span id="secondScore"></span>
        </div>
        <div id="secondRunnerUp">
            <img src="../static/images/first3.png"><br>
            <span id="thirdName"></span> won with <span id="thirdScore"></span>
        </div>
    </div>

    <div id="scoreBoard" hidden>
        <table id="scoreBoardTable" style="left: 35%;top: 10%;border-radius: 0px;border-color: white;">
            <caption>Score Board</caption>
            <thead>
            <tr>
                <th>#</th>
                <th>Usernames</th>
                <th>Score</th>
            </tr>
            </thead>
        </table>
    </div>

    <audio controls hidden autoplay loop="loop">
        <source src="../static/audio/student_quiz_music.mp3" type="audio/mpeg">
    </audio>
    </body>
{% endblock %}

app_pkg/templates/quizstudent.html
{% extends "base.html" %}
{% block content %}
    <!-- body class="login" -->
    <div class="login">
        <div class="header">
            <nav>
                <image src="../static/css/logo.png" class="logo"></image>
                <h1><a href="/">Happy Learning</a></h1>
            </nav>
        </div>
        <!-- <div class="loginbox">
            <form>
                <div class="welcome">
                    <h1>Welcome</h1>
                    <h3>Login into your account</h3>
                </div>
                <p>Username or email</p>
                <input type="text" name="" placeholder="Enter Username"/>
                <p>Password:</p>
                <input type="password" name="" placeholder="Enter password"/>

                <br>

                <label><input type="checkbox">Remember me</label>
                <br>
                <input type="submit" name="" value="Login">
                
                <a href="#">Forgot password?</a>
                <a href="/signup">Don't have an account?</a>
            </form>
        </div> -->
    </div>
{% endblock %}

app_pkg/templates/signin.html
{% extends "base.html" %}
{% block content %}
    <div class="login">
        <div class="header">
            <nav>
                <image src="../static/images/logo.png" class="logo"></image>
                <h1><a href="/">Happy Learning</a></h1>
                <label for="tips">{{ tips }}</label>
            </nav>
        </div>
        <div class="login-box">
            <div class="welcome">
                <h1>Welcome</h1>
                <h3>Login into your account</h3>
            </div>
            <form name="login-form" action="/login_check" method="post" autocomplete="on">
                <p>
                    {{ form.email.label }}<br>
                    {{ form.email(size=32) }}
                </p>
                <p>
                    {{ form.password.label }}<br>
                    {{ form.password(size=32) }}
                </p>
                <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
                <p>{{ form.submit() }}</p>
            </form>
            <a href="#">Forgot password?</a>
            <a href="/signup">Don't have an account?</a>
        </div>
    </div>
{% endblock %}